allowBuilds:
  "@firebase/util": true
  "@swc/core": true
  esbuild: true
  protobufjs: true
  re2: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@swc/core"
  - esbuild
  - protobufjs
  - re2
  - sharp
  - unrs-resolver
