import React from 'react';
import { Trophy, Flame, ChevronRight, RefreshCw, Star, HelpCircle } from 'lucide-react';
import { motion } from 'motion/react';

interface VictoryOverlayProps {
  expression: string;
  score: number;
  streak: number;
  bestStreak: number;
  allSolutions: string[];
  onNext: () => void;
  onReset: () => void;
}

export const VictoryOverlay: React.FC<VictoryOverlayProps> = ({
  expression,
  score,
  streak,
  bestStreak,
  allSolutions,
  onNext,
  onReset
}) => {
  // Filter out redundant spacing and display first 5 alternate solutions nicely
  const displaySolutions = allSolutions
    .filter(sol => sol !== expression)
    .slice(0, 5);

  return (
    <div className="fixed inset-0 bg-slate-950/90 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div 
        className="w-full max-w-lg bg-slate-900 border-2 border-emerald-500/30 rounded-3xl p-6 md:p-8 shadow-[0_0_50px_rgba(16,185,129,0.25)] text-center relative overflow-hidden animate-[float_4s_infinite_ease-in-out]"
      >
        {/* Sparkle backgrounds */}
        <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-emerald-500 via-teal-400 to-emerald-500" />
        
        {/* Animated Celebration Banner */}
        <div className="flex justify-center mb-4">
          <div className="relative">
            <div className="absolute inset-0 bg-emerald-500/20 rounded-full blur-xl animate-pulse" />
            <div className="h-16 w-16 bg-gradient-to-br from-emerald-400 to-teal-500 rounded-full flex items-center justify-center text-slate-900 shadow-lg">
              <Trophy className="h-8 w-8 animate-[bounce_1.5s_infinite]" />
            </div>
          </div>
        </div>

        <h1 className="text-3xl md:text-4xl font-black text-emerald-400 tracking-tight mb-1">
          SUCCEEDED!
        </h1>
        <p className="text-slate-400 text-sm mb-6">Excellent fractional combination logic.</p>

        {/* The winning combined equation */}
        <div className="bg-slate-950/80 rounded-2xl p-4 mb-6 border border-slate-800">
          <span className="text-xs text-slate-400 font-mono block uppercase tracking-wider mb-1">
            Your Winning Combination
          </span>
          <span className="text-xl md:text-2xl font-black text-indigo-300 font-sans tracking-wide">
            {expression} = 24
          </span>
        </div>

        {/* Current statistics */}
        <div className="grid grid-cols-3 gap-2 mb-6">
          <div className="bg-slate-850 p-3 rounded-xl border border-slate-800 flex flex-col items-center">
            <span className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Streak</span>
            <div className="flex items-center gap-1 mt-1 text-orange-400 font-bold text-lg">
              <Flame className="h-4 w-4 fill-orange-500/20" />
              {streak}
            </div>
          </div>
          <div className="bg-slate-850 p-3 rounded-xl border border-slate-800 flex flex-col items-center">
            <span className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Score</span>
            <div className="flex items-center gap-1 mt-1 text-emerald-400 font-bold text-lg">
              <Star className="h-4 w-4 fill-emerald-500/20" />
              {score}
            </div>
          </div>
          <div className="bg-slate-850 p-3 rounded-xl border border-slate-800 flex flex-col items-center">
            <span className="text-[10px] text-slate-400 uppercase tracking-widest font-mono">Best Streak</span>
            <div className="flex items-center gap-1 mt-1 text-indigo-400 font-bold text-lg">
              <Trophy className="h-4 w-4" />
              {bestStreak}
            </div>
          </div>
        </div>

        {/* Alternative solutions generated by the solver */}
        {displaySolutions.length > 0 && (
          <div className="text-left bg-slate-950/40 rounded-xl p-4 border border-slate-800/80 mb-6 max-h-40 overflow-y-auto custom-scrollbar">
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2 flex items-center gap-1.5 font-mono">
              <HelpCircle className="h-3 w-3 text-indigo-400" /> Did you know? Other ways to solve:
            </h3>
            <ul className="space-y-1.5 font-mono text-xs text-slate-300">
              {displaySolutions.map((sol, index) => (
                <li key={index} className="flex items-center gap-1.5">
                  <span className="text-[10px] text-indigo-500/60 font-semibold">{index + 1}.</span>
                  <span className="bg-slate-800/60 px-1.5 py-0.5 rounded border border-slate-800 text-indigo-200">
                    {sol}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3">
          <button
            onClick={onReset}
            className="flex-1 px-5 py-3 rounded-xl bg-slate-800 hover:bg-slate-705 border border-slate-700 hover:border-slate-600 text-slate-300 font-medium transition-all duration-200 flex items-center justify-center gap-2"
          >
            <RefreshCw className="h-4 w-4" /> Replay Puzzle
          </button>
          <button
            onClick={onNext}
            className="flex-[2] px-5 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-slate-900 font-black tracking-wide shadow-lg shadow-emerald-500/20 active:scale-98 transition-all duration-200 flex items-center justify-center gap-2"
          >
            Next Level <ChevronRight className="h-5 w-5 stroke-[2.5]" />
          </button>
        </div>
      </div>
    </div>
  );
};
